### PR TITLE
Updated and modernized

### PR DESCRIPTION
**Pull request by phpfui**
Updated and modernized with namespaces, autoloading, composer and Whitesmiths indenting.

### CODE REVIEW

**Comment by TheDigitalOrchard** [comment]
This pull request was submitted April 13, but there's been no movement since then? Is this project still alive?

**Comment by chewett** [comment]
It looks like this library currently isn't being updated.

If I fork it can I pull your changes in @phpfui ?

**Comment by phpfui** [comment]
I would just use my fork. Fully supported and on packagist.
https://packagist.org/packages/phpfui/icalendar

**Comment by phpfui** [comment]
Just checked the latest commits from the original repo, I had previously
fixed most (porting to newer versions of PHP), but I did find one issue
with addNote (duplicating first node added) that should now be fixed.

Bruce

**Pull request closed without merging**
